### ISSUE TITLE
GDFFlasher -l  list devices on MacOS

### ISSUE THREAD

**Issue by xavax59** [dresden-elektronik/gcfflasher#2]
Hello,

My conbee 2 is connected on Mac0S and the command
./GCFFlasher -l
0 devices found

i have to install a driver on macOS ? 
Thanks

**Comment by manup** [comment]
In the current version the listing of devices is not implemented on macOS but will follow after the Windows port is completet.
Note to myself: need to add this in the `-l` print statement as note.

You don't need to install any drivers, as macOS already contains a default one for USB modems.
The respective device file can be found with `ls /dev/cu.usbmodem*`.

> On macOS the -d parameter is /dev/cu.usbmodemDE... where ... is the serialnumber.

**Comment by manup** [comment]
In the current version the listing of devices is not implemented on macOS but will follow after the Windows port is completed.
Note to myself: need to add this in the `-l` print statement as note.

You don't need to install any drivers, as macOS already contains a default one for USB modems.
The respective device file can be found with `ls /dev/cu.usbmodem*`.

> On macOS the -d parameter is /dev/cu.usbmodemDE... where ... is the serialnumber.
