### ISSUE TITLE
Firmware update unsuccesful 

### ISSUE THREAD

**Issue by chehlo** [dresden-elektronik/gcfflasher#3]
Hi, 

I have a Conbee 2 device running version:  "deCONZ firmware version 26660700" 
I'm trying to update to latest or next version (i have tried both). And in both cases i'm getting error: 
"query bootloader failed" 
With Older version of flasher 
"could not sync with bootloader" 

Command i'm running : 
/GCFFlasher -l
1 devices found
DEV [0]: name: ConBee_II (DE2420389),path: /dev/ttyACM0 --> /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2420389-if00

/GCFFlasher -t 10 -d /dev/ttyACM0 -f ../deCONZ_ConBeeII_0x26720700.bin.GCF 
read file success: ../deCONZ_ConBeeII_0x26720700.bin.GCF (164241 bytes)
flash firmware
query bootloader id
query bootloader id
bootloader detected (60)
failed to sync bootloader (0) 

I have tried with longer timeout same result. 
I disconnected all other devices from usb ports. I'm running on Ubuntu and i have an extension cable.
Any suggestions ? I was able to work with current version but it's started to loose devices and i trying to update fw it's not working at all any more. 

Thanks, 
Ilya.

**Comment by chehlo** [comment]
Don't know if it's helps but -c command output : 
./GCFFlasher -t 10 -d /dev/ttyACM0 -c
packet: 7 bytes, 0E010007008100
packet: 7 bytes, 0E02000700A200
packet: 8 bytes, 0702000800A20000
packet: 8 bytes, 0702000800A20000
packet: 8 bytes, 0702000800A20000
packet: 8 bytes, 0702000800A20000
packet: 8 bytes, 0702000800A20000
packet: 8 bytes, 0702000800A20000
packet: 8 bytes, 0702000800A20000
packet: 8 bytes, 0702000800A20000

**Comment by chehlo** [comment]
From deCONZ log i see: 
08:40:08:220 void zmMaster::handleStateBusy(zmMaster::MasterEvent) unhandled event EVENT_GOT_STATUS
08:40:08:298 command queue EVENT_TIMEOUT, cmd: CMD_READ_PARAM, seq: 213
08:40:08:463 void zmMaster::handleStateStatus(zmMaster::MasterEvent) EVENT_TIMEOUT

**Comment by chehlo** [comment]
after many tests moved to another usb port and was able to update fw successfully

**Comment by manup** [comment]
Interesting since you already use an USB extension cable, interference and stability issues are often fixed by this.

**Comment by chehlo** [comment]
well i did not debugged it further. 
If needed i can
