### ISSUE TITLE
GCFFLASHER - Reboot the key

### ISSUE THREAD

**Issue by VKL-Raziel** [dresden-elektronik/gcfflasher#8]
Hello,

I have Xiaomi buttons that disconnect, to reconnect them I have to reboot the conbee II key on deconz.
I would like to industrialize this, do you have a specific command or other to restart the key without affecting the configuration ?

Does the  "-r" command of GCFFLASHER do what I'm looking for without affecting the configuration of my key ?

Thanks.

**Comment by manup** [comment]
Hi, yes the `-r` option sends a command to the firmware to reboot the ConBee II.
