### ISSUE TITLE
flashing ... retry, failed

### ISSUE THREAD

**Issue by danube** [dresden-elektronik/gcfflasher#9]
I seem to have a disagreement with GCFFlasher when it comes to flashing RaspBee II firmware. It reports "failed" where it has obviously done a good job. Further, it seems to do the job twice, dunno if that's okay.

I followed this procedure: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually#update-in-raspbian

On shell, i see:
`pi@rpi4:/tmp $  sudo GCFFlasher_internal -t 60 -f deCONZ_RaspBeeII_0x26720700.bin.GCF`
`GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh`
`Reboot device RaspBee (RaspBee)`
`deCONZ firmware version 26610700`
`Bootloader version 0x00030003, app crc: 0x769F0F78`
`flashing 164227 bytes: |================|Reboot device RaspBee (RaspBee)`
`deCONZ firmware version 26720700`
`Bootloader version 0x00030003, app crc: 0x01BB96DC`
`flashing 164227 bytes: |================|retry, failed`

In Phoscon web app, it shows the new firmware version correctly, so I assume the process was successful.

In the [deconz-rest-plugin](https://github.com/dresden-elektronik/deconz-rest-plugin) repo, there seems to be [a report with kinda same experience](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5930), @Mimiix gave the request to use this repo instead for reporting.

I use a Rpi4 with RaspBee II and tried to flash firmware deCONZ_RaspBeeII_0x26720700.bin.GCF

Let me know if you need something.

**Comment by KiwiKilian** [comment]
Just experienced the same for upgrading my RaspBee II from `26720700` to `26780700`.

```console
pi@homebridge:/tmp $ sudo GCFFlasher_internal -t 60 -f deCONZ_RaspBeeII_0x26780700.bin.GCF 
GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device RaspBee (RaspBee)
deCONZ firmware version 26720700
Bootloader version 0x00030003, app crc: 0x01BB96DC
flashing 163230 bytes: |================|Reboot device RaspBee (RaspBee)
deCONZ firmware version 26780700
Bootloader version 0x00030003, app crc: 0x8F62A185
flashing 163230 bytes: |================|retry, failed
```

**Comment by manup** [comment]
Closing this for now, the recent GCFFlasher v4.x versions should work fine and deCONZ is shipping these instead of old 3.17 version.
